server:
  port: 8083
  error:
    include-message: always

spring:
  data:
    mongodb:
      database: library-management-system
      host: localhost
      port: 27017

management:
  endpoint:
    health:
      show-components: always
      show-details: always
